version: "3.7"
services:
  mpapi:
    container_name: card-api-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    environment:
      LOGIN: ${LOGIN}
      PASSWORD: ${PASSWORD}
      TOKEN_SECRET: ${TOKEN_SECRET}
    working_dir: /usr/src/card-api
    command: bash -c "yarn install --only=prod && yarn start"
    ports:
      - 5000:5000
      - 9222:9222